env:
  browser: false
  commonjs: true
  es2021: true
  jest: true
extends:
  - standard
  - eslint:recommended
parserOptions:
  ecmaVersion: latest
rules: {
  "semi": ["error", "always"],
  "space-before-function-paren": ["error", {
        "anonymous": "always",
        "named": "never",
        "asyncArrow": "always"
    }]
}
