AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Small Improvements Slack Bot
Resources:
##########################################################################
#   Lambda Function                                                      #
##########################################################################
  SmallImprovementsBotLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: index.handler
      Runtime: nodejs16.x
      Timeout: 300
      Environment:
        Variables:
          DatabaseTable: !Ref DynamoTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoTable
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: 'arn:aws:secretsmanager:us-east-1:729161019481:secret:SIBot-Tokens-J4t6Af'
      Events:
        CWSchedule:
          Type: Schedule
          Properties:
            Schedule: 'cron(0 8,20 ? * MON-FRI *)' # this should be 12 hours for prod #cron(0 8,20 * * MON-FRI *) doesn't work # rate(12 hours)
            Name: SmallImprovementsBotTrigger
            Description: Event to trigger the small improvements slack bot to post completed goals
            Enabled: false # Needs to be true in prod


        
##########################################################################
#   DynamoDB                                                            #
##########################################################################
  DynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: small-improvements-goals
      AttributeDefinitions:
      - AttributeName: "ID"
        AttributeType: "S"
      KeySchema:
      - AttributeName: ID
        KeyType: HASH
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 10
        WriteCapacityUnits: 5
      TimeToLiveSpecification:
        AttributeName: TTL
        Enabled: true
  