AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Need to write a better description
Resources:
##########################################################################
#   Lambda Function                                                      #
##########################################################################
  LambdaForDynamoDB:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: index.handler
      Runtime: nodejs12.x
      Timeout: 300
      Environment:
        Variables:
          DatabaseTable: !Ref DynamoTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoTable
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: 'arn:aws:secretsmanager:us-east-1:729161019481:secret:SIBot-Tokens-J4t6Af'
      Events:
        CWSchedule:
          Type: Schedule
          Properties:
            Schedule: 'rate(2 minutes)' # this should be 12 hours for prod
            Name: TestSchedule
            Description: test schedule
            Enabled: true


        
##########################################################################
#   DynamoDB                                                            #
##########################################################################
  DynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: small-improvements-goals
      AttributeDefinitions:
      - AttributeName: "ID"
        AttributeType: "S"
      KeySchema:
      - AttributeName: ID
        KeyType: HASH
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 10
        WriteCapacityUnits: 5
  