AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Need to write a better description
Parameters:
  SIToken:
    Type: String
    Default: 'a really obviously incorrect string'
Resources:
##########################################################################
#   Lambda Function                                                      #
##########################################################################
  LambdaForDynamoDB:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: index.handler
      Runtime: nodejs12.x
      Timeout: 300
      Environment:
        Variables:
          SIToken: !Ref SIToken
          DatabaseTable: !Ref DynamoTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoTable
      Events:
        CWSchedule:
          Type: Schedule
          Properties:
            Schedule: 'rate(1 minute)' # this should be 12 hours for prod
            Name: TestSchedule
            Description: test schedule
            Enabled: true


        
##########################################################################
#   DynamoDB                                                            #
##########################################################################
  DynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: small-improvements-goals
      AttributeDefinitions:
      - AttributeName: "ID"
        AttributeType: "S"
      - AttributeName: "LastUpdated"
        AttributeType: "N"
      KeySchema:
      - AttributeName: ID
        KeyType: HASH
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 10
        WriteCapacityUnits: 5
  