name: Deployment


on:
  workflow_dispatch: {}
  push:
    branches:
      - main
      - dev

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  build:
    name: Build
    runs-on: "ubuntu-latest"
    steps:
      - name: Install Node 16
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm install
      - run: npm test


  deploy:
    name: Deploy
    runs-on: "ubuntu-latest"
    steps:
      - name: Install Node 16
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3

      - uses: aws-actions/setup-sam@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.DEV_ROLE_ARN }}
          role-session-name: DeployToProd
      # sam build
      - run: sam build --use-container
      # Run unit tests here
      - run: npm test
      # sam deploy
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset