name: Deployment

on: 
  push:
    branches:
      - main
      - dev

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  build:
    name: Build
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: Install Node 16
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - run: npm ci
      - run: npm test

  deploy-dev:
    name: Deploy-dev
    needs: Build
    uses: ./.github/workflows/reusable-builder.yml
    with:
      ROLE_ARN: ${{ secrets.DEV_ROLE_ARN }}
      SESSIONNAME: DeployToDev
    
        

  deploy-prod:
    name: Deploy-prod
    needs: Deploy-dev
    uses: ./.github/workflows/reusable-builder.yml
    with:
      ROLE_ARN: ${{ secrets.PROD_ROLE_ARN }}
      SESSIONNAME: DeployToProd
    
        
